Various fixes for issues found by the audit
IntersectMBO/formal-ledger-specifications pull request #425
Opened 2024-05-10 13:26 UTC by WhatisRT

# Description

There were smaller changes that I made while responding to the audit.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] Code is formatted according to [CONTRIBUTING.md](https://github.com/input-output-hk/formal-ledger-specifications/blob/master/CONTRIBUTING.md)
- [x] Self-reviewed the diff

2024-05-21 17:39 UTC, williamdemeo requested changes
I've suggested a couple of minor changes, but feel free to ignore these changes.  More importantly, the latest master needs to be merged into this branch and conflicts must be resolved.  (I merged the latest master into my local checkout of this branch and reconciled the conflicts in a way that seemed most reasonable to me.  I could push that to this branch, but it's probably safer for you to resolve the conflicts yourself.  The main non-trivial conflict is that master now defines a `keyDeposit` parameter which is used instead of `poolDeposits` in the `Deleg` module.

2024-05-21 17:39 UTC, williamdemeo commented on src/Ledger/Enact.lagda
> +consequences. \TreasuryWdrl accumulates withdrawal temporarily in \EnactState
```suggestion
consequences. \TreasuryWdrl accumulates withdrawal temporarily in \EnactState,
```

2024-05-21 17:39 UTC, williamdemeo commented on src/Ledger/Gov.lagda
> +role. This means that anyone can vote for e.g. the \CC role. However,
```suggestion
role. This means that anyone can vote for, e.g., the \CC role. However,
```

2024-05-21 17:39 UTC, williamdemeo commented on src/Ledger/Notation.lagda
> +  \AgdaBound{m}~\AgdaFunction{∪⁺}~\AgdaBound{m'} for their union where keys that appear
```suggestion
  \AgdaBound{m}~\AgdaFunction{∪⁺}~\AgdaBound{m'} for their union, where keys that appear
```

2024-05-22 16:32 UTC, WhatisRT commented
@williamdemeo I've incorporated your suggestions, but you still need to approve the PR

2024-05-23 10:22 UTC, WhatisRT commented
@williamdemeo I'm now using my admin powers to merge this PR anyway. Your message sounds like you're fine with merging it, so you should have approved this PR in the UI.

2024-05-23 10:22 UTC, merged