PDF improvements: names and symbols
IntersectMBO/formal-ledger-specifications pull request #496
Opened 2024-07-04 01:03 UTC by williamdemeo

# Description

This addresses some of the items in issue #481.

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Code is formatted according to [CONTRIBUTING.md](https://github.com/input-output-hk/formal-ledger-specifications/blob/master/CONTRIBUTING.md)
- [X] Self-reviewed the diff

2024-07-08 22:30 UTC, williamdemeo commented
Just two items left to do.

- [ ] [Lines 83--86](https://github.com/IntersectMBO/formal-ledger-specifications/blob/52e31136cdfb6e38130cacaed75392fece71c0a2/src/Ledger/Introduction.lagda#L82C1-L87C1) of `Introduction.lagda`: The symbol `X` is not defined.
- [ ] [Line 211](https://github.com/IntersectMBO/formal-ledger-specifications/blob/52e31136cdfb6e38130cacaed75392fece71c0a2/src/Ledger/Utxo.lagda#L211) of `Utxo.lagda`: ∑[_←_] is not defined.

2024-07-09 11:26 UTC, WhatisRT requested changes

2024-07-09 14:25 UTC, williamdemeo commented on src/Ledger/Utxow.lagda
> +    ∙  txADhash ≡ mapᴸ hash txAD
I don't know how to fix this with a LaTeX macro. That's why I used Agda renaming.  Can you explain how you would do it with macros here or in the meeting today?

2024-07-09 14:37 UTC, WhatisRT commented on src/Ledger/Utxow.lagda
> +    ∙  txADhash ≡ mapᴸ hash txAD
Just do `\newunicodechar{ˢ}{}`.

2024-07-09 14:54 UTC, williamdemeo commented on src/Ledger/GovernanceActions.lagda
> +\Unit is the unit type that has exactly one element, which reflects
The sentence is not just re-explaining the unit.  It is also explaining *why* it's used here.

2024-07-09 22:53 UTC, williamdemeo commented on src/Ledger/Utxow.lagda
> +    ∙  txADhash ≡ mapᴸ hash txAD
I tried the newunicodechar trick as well as DeclareUnicodeChar.  Neither worked for me, so I added another postprocessing python script which simply replaces each occurrence of `mapˢ` with `map`.

2024-07-09 22:54 UTC, williamdemeo commented on src/Ledger/GovernanceActions.lagda
> +\Unit is the unit type that has exactly one element, which reflects
I've removed explanation of unit from `GovernanceActions` and added a more general description of that type to `Notation`.

2024-07-10 15:19 UTC, WhatisRT commented on src/Ledger/Utxow.lagda
> +    ∙  txADhash ≡ mapᴸ hash txAD
I just put `\newunicodechar{ˢ}{\ensuremath{}}` and it works, so no need for another script.

2024-07-10 15:43 UTC, williamdemeo commented on src/Ledger/Utxow.lagda
> +    ∙  txADhash ≡ mapᴸ hash txAD
`\ensuremath{}` must insert the "missing" $ that latex was complaining about.  Good.

2024-07-10 15:47 UTC, williamdemeo commented on src/Ledger/Utxow.lagda
> +    ∙  txADhash ≡ mapᴸ hash txAD
Weird.  It works when I put it in `preamble.tex` but not when I put it in `iohk.sty`.

2024-07-11 11:11 UTC, WhatisRT approved these changes
LGTM

2024-07-11 11:12 UTC, merged